name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  kira-artifacts:
    uses: ./.github/workflows/_kira-artifacts.yml
    with:
      publish_release: true
    secrets: inherit
